### ISSUE TITLE
Add more metacity themes

### ISSUE THREAD

**Issue by City-busz** [charlesbos/metacity-themes#5]
There are some more old metacity themes available, which are unmaintained now. Please consider adding them to the project:
- [Clearlooks](https://git.gnome.org/browse/archive/gnome-themes/tree/metacity-themes/Clearlooks)
- [ClearlooksClassic](https://git.gnome.org/browse/archive/gnome-themes/tree/metacity-themes/ClearlooksClassic)
- [Glider](https://git.gnome.org/browse/archive/gnome-themes/tree/metacity-themes/Glider)
- [Glossy](https://git.gnome.org/browse/archive/gnome-themes/tree/metacity-themes/Glossy)
- [Gorilla](https://git.gnome.org/browse/metacity/tree/src/themes/Gorilla?id=ff896d7d7e28a29ef104003f9e7a437a5da7f46c)
- [Inverted](https://git.gnome.org/browse/archive/gnome-themes/tree/metacity-themes/Inverted)
- [Mist](https://git.gnome.org/browse/archive/gnome-themes/tree/metacity-themes/Mist)
- [Unity](https://git.gnome.org/browse/archive/gnome-themes-extras/tree/metacity-themes/Unity)

**Comment by charlesbos** [comment]
Thanks for bringing these to my attention. I'll have a look at adding them shortly.

**Comment by charlesbos** [comment]
All added and released.
